from pathlib import Path
import json,hashlib,re,shutil,difflib
P=Path('/Volumes/Macintosh_HD/Users/user302070/Documents/Codex/2026-09-08/start-from-commit-f377dcac-and-read/work/northern-canopy-free-family-pilot-001');D=P/'1397-live-preparation-001';W=P/'1397-1226-live-preparation-001';W.mkdir();S=W/'source';shutil.copytree(D/'source',S);H=P/'1205-1226-band-visibility-003';HR=Path(json.loads((H/'FILE_READY.json').read_text())['checkout']);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text());save=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n')
for rel in ['comparison','baseline-world.json','accepted-registry-before.json','focused_live_contract.gd','observed_builder.gd','unit-expectations.json','package-consumer-plan.json','source-run-plan.json','run-stage.py','run-reviewed-chain.py','release.py','materialize-source.py']:
 p=D/rel
 if p.is_dir():shutil.copytree(p,W/rel)
 else:shutil.copyfile(p,W/rel)
old=(HR/'game/scripts/world/facades/bayside_1226_study.gd').read_text();f=old.replace('## Isolated 1226 art study; deliberately not registered with the live adapter.','## Exact H003 construction supplied through live caller callbacks.').replace('const BUILDER := preload("res://game/scripts/world/world_chunk_builder.gd")\n','').replace('bayside_1226_study.gd','bayside_1226_live_factory.gd').replace('var _last_result: Dictionary = {}','var _last_result: Dictionary = {}\nvar _tangent_builder: Callable').replace('roof: Dictionary, baseline: bool = false','roof: Dictionary, source_builder: Callable, tangent_builder: Callable, baseline: bool = false').replace('"configure_records", wall, roof, baseline','"configure_records", wall, roof, source_builder, tangent_builder, baseline').replace('\tif not matches_record_pair(wall, roof): return','\tif not source_builder.is_valid() or not tangent_builder.is_valid(): return {"ok": false, "message": "Original source and tangent producers required."}\n\t_tangent_builder = tangent_builder\n\tif not matches_record_pair(wall, roof): return').replace('\tvar builder := BUILDER.new()\n\tvar originals: Array = [builder._build_record(wall, false), builder._build_record(roof, false)]','\tvar originals: Array = [source_builder.call(wall, false), source_builder.call(roof, false)]').replace('BUILDER.new()._tangents_for(', '_tangent_builder.call(');assert 'BUILDER'not in f;(S/'game/scripts/world/facades/bayside_1226_live_factory.gd').write_text(f)
config=HR/'game/resources/facades/bayside_1226_study.json';assert not re.search(r'/Volumes/|/Users/|https?://',config.read_text());shutil.copyfile(config,S/'game/resources/facades/bayside_1226_study.json');a=read(H/'focused-1226-003-result.json');meta=a['metadata'];a=(S/'game/scripts/world/facades/gateview_1397_live_replacement.gd').read_text();a=a.replace('gateview_1397','bayside_1226').replace('gateview-1397','bayside-1226').replace('Gateview1397','Bayside1226').replace('1397 Gateview','1226 Bayside').replace('1397','1226').replace('w96215670','w96215685').replace('"x_-1__z_-3"','"x_-2__z_-3"')
for name,value in [('EXPECTED_FACTORY_SHA256',sha(S/'game/scripts/world/facades/bayside_1226_live_factory.gd')),('EXPECTED_CONFIG_SHA256',sha(config))]:a=re.sub(r'(const '+name+r' := ")[a-f0-9]{64}',r'\g<1>'+value,a)
for name,key in [('MAPPED_RUNS','mapped_public_run_indices'),('PROTECTED_RUNS','protected_run_indices')]:a=re.sub(r'const '+name+r' := \[[^\n]+\]', 'const '+name+' := '+json.dumps(meta[key]),a)
(S/'game/scripts/world/facades/bayside_1226_live_replacement.gd').write_text(a)
b=(S/'game/scripts/world/world_chunk_builder.gd').read_text();clone=lambda z:z.replace('GATEVIEW_1397','BAYSIDE_1226').replace('gateview_1397','bayside_1226').replace('1397','1226').replace('w96215670','w96215685')
line=next(x for x in b.splitlines()if x.startswith('const GATEVIEW_1397'));b=b.replace(line,line+'\n'+clone(line))
for begin,finish in [('\tvar gateview_1397_pair :=','\t\treturn gateview_1397_pair'),('\tvar gateview_1397_plan :=','\trollback_plans.append({"adapter": GATEVIEW_1397')]:
 start=b.index(begin);end=b.index('\n',b.index(finish,start))+1;b=b[:end]+clone(b[start:end])+b[end:]
line=next(x for x in b.splitlines()if 'var record_result := _build_record('in x);b=b.replace(line,line.replace(', gateview_1397_plan)',', gateview_1397_plan, bayside_1226_plan)'));b=b.replace(', gateview_1397_plan: Dictionary = {})',', gateview_1397_plan: Dictionary = {}, bayside_1226_plan: Dictionary = {})');line='\tvar gateview_1397_consumed := GATEVIEW_1397_LIVE_REPLACEMENT.plan_was_fully_consumed(gateview_1397_plan)';b=b.replace(line,line+'\n'+clone(line)).replace('or not gateview_1397_consumed:','or not gateview_1397_consumed or not bayside_1226_consumed:');start=b.index('\t\tif not gateview_1397_consumed:');end=b.index('\n',b.index('\t\t\treturn ',start))+1;b=b[:end]+clone(b[start:end])+b[end:];needle='\tif not is_context and GATEVIEW_1397_LIVE_REPLACEMENT.claims_record(record):\n\t\treturn GATEVIEW_1397_LIVE_REPLACEMENT.consume_record(record, gateview_1397_plan)';assert b.count(needle)==1;b=b.replace(needle,needle+'\n'+clone(needle));(S/'game/scripts/world/world_chunk_builder.gd').write_text(b)
# Literal counts derive from the actual frozen H003 result.
mesh=meta['mesh_instances'];tris=meta['visual_triangles'];details=len(read(H/'focused-1226-003-result.json')['detail_collision'])-1;rooftris=meta['visual_batch_triangles']['ExactSourceNeutralRoof'];spec={'prefix':'Bayside1226Live','wall':dict(meshes=mesh-1,surfaces=mesh-1,triangles=tris-rooftris,bodies=3,shapes=details+2),'roof':dict(meshes=1,surfaces=1,triangles=rooftris,bodies=1,shapes=1),'detail_shapes':details,'meshes':mesh,'channels':mesh*13,'shapes':details+3,'detail_tangents':mesh-2,'projected_runs':meta['mapped_public_run_indices'],'projected_triangles':meta['visual_batch_triangles']['ProjectedUpperSiding'],'public_roof':True};m=(S/'game/scripts/main.gd').read_text();needle='func _mac_export_projected_family_spec(adapter: Script) -> Dictionary:\n\tmatch str(adapter.SOURCE_KEY):';assert m.count(needle)==1;m=m.replace(needle,needle+'\n\t\t"w96215685": return '+json.dumps(spec));(S/'game/scripts/main.gd').write_text(m);save(W/'1226-unit-spec.json',spec)
(W/'1226-study-to-live.diff').write_text(''.join(difflib.unified_diff(old.splitlines(True),f.splitlines(True),fromfile=str(HR/'game/scripts/world/facades/bayside_1226_study.gd'),tofile='live-factory')));save(W/'SOURCE_ORIGINS.json',{'1397_unchanged_selected':{rel:h for rel,h in read(D/'selected-files.json').items()if 'gateview_1397' in rel},'1397_readiness':str(D/'independent-readiness-001/READINESS.md'),'1226_factory':{'path':str(HR/'game/scripts/world/facades/bayside_1226_study.gd'),'sha256':sha(HR/'game/scripts/world/facades/bayside_1226_study.gd')},'1226_config':{'path':str(config),'sha256':sha(config)},'1226_actual_source':{'path':str(H/'focused-1226-003-result.json'),'sha256':sha(H/'focused-1226-003-result.json')}})
print('shared source prepared',spec)
