from pathlib import Path
import json,hashlib,re,shutil
P=Path('/Volumes/Macintosh_HD/Users/user302070/Documents/Codex/2026-09-08/start-from-commit-f377dcac-and-read/work/northern-canopy-free-family-pilot-001');D=P/'1397-live-preparation-001';W=P/'1397-1226-live-preparation-001';S=W/'source';H=P/'1205-1226-band-visibility-003';HR=Path(json.loads((H/'FILE_READY.json').read_text())['checkout']);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text());save=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n')
p=W/'focused_live_contract.gd';s=p.read_text().replace(str(D),str(W));s=s.replace('specs.size()==1 and specs.map(func(s):return str(s.number))==["1397"]','specs.size()==2 and specs.map(func(s):return str(s.number))==["1397","1226"]').replace('The exact1397 batch','The exact1397+1226 batch').replace('Actual accepted1397 source/mechanics/motion evidence','Actual accepted1397 and1226 source/mechanics/motion evidence').replace('GATEVIEW1397_LIVE_FOCUSED_','GATEVIEW1397_BAYSIDE1226_LIVE_FOCUSED_').replace('source-bound1397 addition','source-bound1397 and1226 additions');p.write_text(s)
p=W/'observed_builder.gd';s=p.read_text().replace(', gateview_1397_plan: Dictionary = {})',', gateview_1397_plan: Dictionary = {}, bayside_1226_plan: Dictionary = {})').replace(', gateview_1397_plan)',', gateview_1397_plan, bayside_1226_plan)');p.write_text(s)
p=W/'comparison/study-1397.gd';p.write_text(p.read_text().replace(str(D),str(W)));p=W/'comparison/study-1226.gd';s=(HR/'game/scripts/world/facades/bayside_1226_study.gd').read_text().replace('preload("res://game/scripts/world/world_chunk_builder.gd")','preload("'+str(W/'comparison/current-chunk-builder.gd')+'")').replace('"res://game/scripts/world/facades/bayside_1226_study.gd"','"'+str(p)+'"');p.write_text(s)
meta=read(H/'focused-1226-003-result.json')['metadata'];spec=read(W/'1226-unit-spec.json');u={'number':'1226','stem':'bayside_1226','source_key':'w96215685','chunk':'x_-2__z_-3','neighbor':'x_-1__z_-3','factory':'game/scripts/world/facades/bayside_1226_live_factory.gd','wrapper':'game/scripts/world/facades/bayside_1226_live_replacement.gd','config':'game/resources/facades/bayside_1226_study.json','study_factory_sha256':sha(HR/'game/scripts/world/facades/bayside_1226_study.gd'),'current_art_receipt':str(H/'focused-1226-003-result.json'),'current_art_receipt_sha256':sha(H/'focused-1226-003-result.json'),'mesh_count':spec['meshes'],'surface_count':spec['meshes'],'total_triangles':meta['visual_triangles'],'total_bodies':4,'total_shapes':spec['shapes'],'detail_shape_count':spec['detail_shapes'],'added_mesh_count':spec['meshes']-2,'added_shape_count':spec['shapes']-2,'added_triangles':meta['visual_triangles']-meta['visual_batch_triangles']['ExactOriginalWallSurfaces']-meta['visual_batch_triangles']['ExactSourceNeutralRoof'],'wall_mesh_count':spec['wall']['meshes'],'wall_live_triangles':spec['wall']['triangles'],'wall_bodies':spec['wall']['bodies'],'wall_shapes':spec['wall']['shapes'],'roof_mesh_count':1,'roof_live_triangles':spec['roof']['triangles'],'roof_bodies':1,'roof_shapes':1,'standalone_detail_callbacks':spec['detail_tangents'],'target_records':len(read(S/'generated/world/chunks/x_-2__z_-3.json')['records']),'projected_receiver_runs':spec['projected_runs'],'projected_receiver_triangles':spec['projected_triangles'],'public_roof_detail':True,'baseline_chunk_detail_callbacks':126};units=read(W/'unit-expectations.json');assert len(units)==1;units.append(u);save(W/'unit-expectations.json',units)
oldpins=read(P/'1232-1241-1221-live-preparation-001/source-pins.json');result=P/'1232-1241-1221-live-preparation-001/continuation-001/focused-002-result.json';a=read(result);joins=[];adapters=[]
for p in S.glob('game/scripts/world/facades/*live_replacement.gd'):
 if p.name=='bayside_1226_live_replacement.gd' or not re.search(r'const TARGET_CHUNK_ID\s*:?=\s*"x_-2__z_-3"',p.read_text()):continue
 adapters.append(p.name)
 # Every literal file dependency of the old adapter/factory is independently byte-joined to prior actual pins.
 pending=[p];seen=set()
 while pending:
  f=pending.pop();rel=str(f.relative_to(S))
  if rel in seen:continue
  seen.add(rel);matches=[(k,v)for k,v in oldpins.items()if k.endswith('/'+rel)];assert any(h==sha(f)for k,h in matches),(rel,matches);joins.append({'relative':rel,'sha256':sha(f),'historical_matches':matches})
  if f.suffix not in ['.gd','.json','.tres','.gdshader']:continue
  for dep in re.findall(r'res://([^"\s\)]+)',f.read_text()):
   fp=S/dep
   if fp.is_file() and fp.suffix in ['.gd','.json','.tres','.gdshader'] and 'world_chunk_builder'not in dep:pending.append(fp)
assert a['units']['w96215673']['actual_caller_lifecycle']['normal']['callbacks']['detail_tangent_calls']==126
save(W/'callback-baseline-binding.json',{'1397':read(D/'callback-baseline-binding.json'),'1226':{'actual_result':str(result),'sha256':sha(result),'unit':'w96215673','baseline_callbacks':126,'new_callbacks':14,'expected_total':140,'same_chunk_prior_adapters':adapters,'exact_producer_joins':joins}})
world=read(W/'baseline-world.json')['measured_world'].copy()
for x in units:world['meshes']+=x['added_mesh_count'];world['surfaces']+=x['added_mesh_count'];world['triangles']+=x['added_triangles'];world['bodies']+=2;world['shapes']+=x['added_shape_count']
save(W/'expected-world.json',world);print('shared world',world,'prior adapters',len(adapters),'dependency joins',len(joins))
