extends SceneTree

const EVIDENCE_ROOT := "res://evidence/first-playable/batch-06-w34313525-standalone-prototypes-2026-08-30"
const MANIFEST_PATH := EVIDENCE_ROOT + "/capture-manifest.json"
const VERIFICATION_PATH := EVIDENCE_ROOT + "/verification.json"
const ISOLATION_PATH := EVIDENCE_ROOT + "/runtime-isolation.json"
const README_PATH := EVIDENCE_ROOT + "/README.md"
const CHECKSUMS_PATH := EVIDENCE_ROOT + "/SHA256SUMS.txt"
const EXPECTED_RECORD_HASHES := {
	MANIFEST_PATH: "b7f4bc8e14b74fb95f0eec27043e747f7edff2526e80a614540303a96c1e1de4",
	VERIFICATION_PATH: "60f5f29adca4722a88259fb359a0c46377a0997d9b60f940c8915975c292dad1",
	ISOLATION_PATH: "af85721f89592f4ffa1a5f73526f868a013f42e3868c2ab2c811b9d7867fe995",
	README_PATH: "5015b387e268a3972d53589d87af3b9700358be5545577503498ef2aa86ef456",
	CHECKSUMS_PATH: "1a9e0e09d5fdacc00313763eb4d40d35b9b9efa715242a8523c49dd2e6522092",
}
const EXPECTED_IMAGES := {
	"01-neutral-field-close.png": {"sha256": "c09a9af4a2e768537d592de822fe477bb6445ed132ae0c42ad19356c91d67efb", "bytes": 101433, "view_kind": "neutral_close_material"},
	"02-rollup-pale-close.png": {"sha256": "277106ad3a8402f2bbb14dffbeb9691ff7b240365a1023fdb2175548d1094d61", "bytes": 197404, "view_kind": "complete_module_neutral"},
	"03-rollup-gray-close.png": {"sha256": "a3a6d79d7a6b0beede652c8bf4387911af33ed266c11bbe2a7c709947b395419", "bytes": 211899, "view_kind": "complete_module_neutral"},
	"04-personnel-close.png": {"sha256": "6981bc628dea4549989af15118363c70601981088457f584c5c77bc693680e4d", "bytes": 158413, "view_kind": "complete_module_neutral"},
	"05-high-group-close.png": {"sha256": "b5a31c2b55ab01e582bd000e00d998d21b8394ac643f150b8397c2bb1cf3840a", "bytes": 103141, "view_kind": "complete_module_front"},
	"06-ordinary-complete-set.png": {"sha256": "80964f7117254f6b90883b9a735ef12d299200edc15f0a77ffb05cfe2a9d805a", "bytes": 83864, "view_kind": "ordinary_gameplay_readable_scale"},
	"07-macro-repeat-span.png": {"sha256": "b32a2c2640911f04f1bd0ac61f696de185b0e458b2fcceb6768ef39a5c4fd8d7", "bytes": 74669, "view_kind": "macro_repeat_and_alias_control"},
	"08-changed-light-oblique.png": {"sha256": "6f2ef029cebeafa6827683090c92f805df1669ef2b1e005d2c6fd083554e43c1", "bytes": 136950, "view_kind": "changed_light_oblique_finish_depth_and_backing"},
}
const EXPECTED_RUNTIME_HASHES := {
	"res://discovery/FACADE_RECEIVER_INVENTORY.json": "220f8af84f3f16c104858f630be9c4bb7e2d282569ab4d3a00bd49c07cb0b3cf",
	"res://generated/world/manifest.json": "e501236d0908a1a1fd41b3973e7adbd3e94d32bb658cc3f1e44f7731f00a1fb3",
	"res://generated/world/chunks/x_1__z_-1.json": "a952756b1c6d8d547669dffb89723c2be81d6c9a4b3afd2ae7f2dc3702a82b0d",
	"res://game/scripts/world/world_chunk_builder.gd": "e54b31cef98b45f00aadcba0b7a6dec0125f147c1c332c06158198dbe19e508d",
	"res://game/scripts/world/facades/accepted_material_run_trials.gd": "aaea7d6518fda141a0c488a54a7441a70bc52d5b98cd666876aa665d3b5be80e",
	"res://game/resources/facades/batch_06_prototype_registry.json": "a599df850a3ca51a51a3223820fc840201559ba26eb5ed514211eaedc2304132",
}

var _failed := false


func _initialize() -> void:
	call_deferred("_run")


func _run() -> void:
	if not _require(_hashes_match(EXPECTED_RECORD_HASHES), "A sealed w34313525 evidence record drifted.") \
	or not _require(_hashes_match(EXPECTED_RUNTIME_HASHES), "Runtime, generated data, inventory, or prior Batch 06 registry changed during capture.") \
	or not _require(_evidence_file_set_matches(), "The evidence directory contains a missing or unexpected file."):
		_finish()
		return
	var manifest := JSON.parse_string(FileAccess.get_file_as_string(MANIFEST_PATH)) as Dictionary
	var verification := JSON.parse_string(FileAccess.get_file_as_string(VERIFICATION_PATH)) as Dictionary
	var isolation := JSON.parse_string(FileAccess.get_file_as_string(ISOLATION_PATH)) as Dictionary
	if not _require(_manifest_matches(manifest), "Capture manifest renderer, topology, view coverage, or truth boundary failed.") \
	or not _require(_images_match(manifest), "A PNG byte count, hash, dimensions, view kind, or luminance record failed.") \
	or not _require(_verification_matches(verification), "The capture verification status, correction boundary, or blocked claims failed.") \
	or not _require(_isolation_matches(isolation), "Runtime-isolation before/after proof failed.") \
	or not _require(_checksums_match(), "SHA256SUMS does not exactly seal the final records and images."):
		_finish()
		return
	print("PASS: eight final native 1440x900 Forward+/Metal w34313525 standalone captures are byte-sealed and mechanically valid after one camera-only correction; all five assets have close/ordinary/macro/changed-light coverage, modules retain zero backing, runtime/generated bytes remain unchanged, and every art/exact/live/whole-building verdict remains unreviewed or blocked")
	_finish()


func _manifest_matches(manifest: Dictionary) -> bool:
	if str(manifest.get("schema_version", "")) != "ti.w34313525-standalone-prototype-evidence/1" \
	or str(manifest.get("source_key", "")) != "w34313525" \
	or str(manifest.get("receiver_key", "")) != "building:w34313525:wall" \
	or str(manifest.get("review_status", "")) != "ready_for_independent_standalone_art_review_not_self_accepted" \
	or str(manifest.get("godot_version", "")) != "4.7.2-stable (official)" \
	or str(manifest.get("display_driver", "")) != "macOS" \
	or str(manifest.get("rendering_method", "")) != "Forward+" \
	or str(manifest.get("rendering_driver", "")) != "Metal" \
	or "Apple M1 Pro" not in str(manifest.get("video_adapter", "")) \
	or manifest.get("viewport", []) != [1440.0, 900.0] \
	or bool(manifest.get("runtime_attachment", true)) \
	or bool(manifest.get("exact_receiver_calibration", true)):
		return false
	var kinds := manifest.get("asset_kinds", {}) as Dictionary
	if (kinds.get("homogeneous_material_tile", []) as Array).size() != 1 \
	or (kinds.get("module_atlas", []) as Array).size() != 4 \
	or not (kinds.get("architectural_pattern_tile", []) as Array).is_empty() \
	or not (kinds.get("unique_elevation", []) as Array).is_empty():
		return false
	var topology := manifest.get("topology", {}) as Dictionary
	if int(topology.get("total_meshes", 0)) != 39 \
	or int(topology.get("total_surfaces", 0)) != 39 \
	or int(topology.get("total_triangles", 0)) != 468 \
	or int(topology.get("module_meshes", 0)) != 38 \
	or int((manifest.get("module_proof", {}) as Dictionary).get("field_or_backing_meshes", -1)) != 0:
		return false
	var blocked := JSON.stringify(manifest.get("blocked_claims", [])).to_lower()
	for phrase in ["exact placement", "surveyed dimensions", "repair-patch", "completed sse or nnw", "whole-building"]:
		if phrase not in blocked:
			return false
	return true


func _images_match(manifest: Dictionary) -> bool:
	var captures := manifest.get("captures", []) as Array
	if captures.size() != EXPECTED_IMAGES.size():
		return false
	var seen: Dictionary = {}
	for capture_value: Variant in captures:
		var capture := capture_value as Dictionary
		var filename := str(capture.get("file", ""))
		if not EXPECTED_IMAGES.has(filename) or seen.has(filename):
			return false
		seen[filename] = true
		var expected := EXPECTED_IMAGES[filename] as Dictionary
		var path := EVIDENCE_ROOT.path_join(filename)
		if FileAccess.get_sha256(path) != str(expected.get("sha256", "")) \
		or str(capture.get("sha256", "")) != str(expected.get("sha256", "")) \
		or FileAccess.get_file_as_bytes(path).size() != int(expected.get("bytes", 0)) \
		or int(capture.get("bytes", 0)) != int(expected.get("bytes", 0)) \
		or str(capture.get("view_kind", "")) != str(expected.get("view_kind", "")) \
		or capture.get("dimensions", []) != [1440.0, 900.0]:
			return false
		var image := Image.load_from_file(ProjectSettings.globalize_path(path))
		if image == null or image.is_empty() or image.get_size() != Vector2i(1440, 900):
			return false
		var luminance := capture.get("sampled_luminance", {}) as Dictionary
		if int(luminance.get("sample_count", 0)) != 4000 \
		or float(luminance.get("range", 0.0)) < 0.9 \
		or float(luminance.get("minimum", -1.0)) < 0.0 \
		or float(luminance.get("maximum", 2.0)) > 1.0:
			return false
	return seen.size() == EXPECTED_IMAGES.size()


func _verification_matches(verification: Dictionary) -> bool:
	if str(verification.get("status", "")) != "native_capture_complete_pending_independent_review":
		return false
	var verdict := verification.get("verdict_boundary", {}) as Dictionary
	if str(verdict.get("mechanical_capture_validity", "")) != "pass" \
	or str(verdict.get("semantic_repeat_verdict", "")) != "unreviewed" \
	or str(verdict.get("material_art_verdict", "")) != "unreviewed" \
	or str(verdict.get("standalone_asset_acceptance", "")) != "not_self_accepted" \
	or str(verdict.get("exact_receiver_verdict", "")) != "not_started" \
	or str(verdict.get("whole_building_verdict", "")) != "blocked":
		return false
	var attempts := verification.get("capture_attempts", {}) as Dictionary
	if int(attempts.get("native_pass_count", 0)) != 2 \
	or int(attempts.get("targeted_pose_correction_count", 0)) != 1 \
	or bool(attempts.get("prototype_art_or_geometry_changed", true)) \
	or int(attempts.get("final_image_count", 0)) != 8 \
	or bool(attempts.get("superseded_images_retained", true)):
		return false
	var preflight := verification.get("preflight", {}) as Dictionary
	if bool(preflight.get("owner_treasure_island_or_godot_process_found", true)) \
	or bool(preflight.get("capture_process_found_after_harness_exit", true)) \
	or bool(preflight.get("playable_main_game_launched", true)) \
	or bool(preflight.get("external_resource_used", true)):
		return false
	var coverage := verification.get("coverage", {}) as Dictionary
	for required in ["mat_pale_neutral_close", "mat_pale_changed_light", "rollup_pale_complete_front", "rollup_gray_complete_front", "personnel_complete_front", "personnel_ordinary_scale", "high_group_complete_front", "high_group_oblique", "high_group_ordinary_scale", "combined_ordinary_all_material_families", "combined_changed_light_all_material_families", "zero_module_backing_visible_and_mechanically_proven"]:
		if not bool(coverage.get(required, false)):
			return false
	return is_equal_approx(float(coverage.get("mat_pale_macro_span_m", 0.0)), 30.0)


func _isolation_matches(isolation: Dictionary) -> bool:
	if str(isolation.get("capture_scope", "")) != "native standalone proof scene only" \
	or bool(isolation.get("runtime_loaded_for_capture", true)) \
	or bool(isolation.get("playable_main_scene_launched", true)) \
	or bool(isolation.get("receiver_attachment", true)) \
	or bool(isolation.get("exact_receiver_calibration", true)) \
	or bool(isolation.get("generated_data_changed", true)) \
	or bool(isolation.get("runtime_topology_changed", true)):
		return false
	var records := isolation.get("protected_files", []) as Array
	if records.size() != EXPECTED_RUNTIME_HASHES.size():
		return false
	for record_value: Variant in records:
		var record := record_value as Dictionary
		var path := str(record.get("path", ""))
		if not EXPECTED_RUNTIME_HASHES.has(path) \
		or str(record.get("before_sha256", "")) != str(EXPECTED_RUNTIME_HASHES[path]) \
		or str(record.get("after_sha256", "")) != str(EXPECTED_RUNTIME_HASHES[path]):
			return false
	var topology := isolation.get("unchanged_runtime_topology", {}) as Dictionary
	return int(topology.get("records", 0)) == 729 \
		and int(topology.get("meshes", 0)) == 886 \
		and int(topology.get("surfaces", 0)) == 894 \
		and int(topology.get("triangles", 0)) == 50273 \
		and int(topology.get("collider_pairs", 0)) == 466


func _checksums_match() -> bool:
	var expected_lines: Array[String] = []
	for filename: Variant in EXPECTED_IMAGES:
		expected_lines.append("%s  %s" % [str((EXPECTED_IMAGES[filename] as Dictionary).get("sha256", "")), str(filename)])
	expected_lines.append("%s  capture-manifest.json" % str(EXPECTED_RECORD_HASHES[MANIFEST_PATH]))
	expected_lines.append("%s  runtime-isolation.json" % str(EXPECTED_RECORD_HASHES[ISOLATION_PATH]))
	expected_lines.append("%s  verification.json" % str(EXPECTED_RECORD_HASHES[VERIFICATION_PATH]))
	expected_lines.append("%s  README.md" % str(EXPECTED_RECORD_HASHES[README_PATH]))
	expected_lines.sort()
	var actual_lines := FileAccess.get_file_as_string(CHECKSUMS_PATH).strip_edges().split("\n")
	actual_lines.sort()
	return actual_lines == PackedStringArray(expected_lines)


func _evidence_file_set_matches() -> bool:
	var files := Array(DirAccess.get_files_at(EVIDENCE_ROOT))
	files.sort()
	var expected := Array(EXPECTED_IMAGES.keys())
	expected.append_array(["capture-manifest.json", "verification.json", "runtime-isolation.json", "README.md", "SHA256SUMS.txt"])
	expected.sort()
	return files == expected


func _hashes_match(expected: Dictionary) -> bool:
	for path_value: Variant in expected:
		var path := str(path_value)
		if FileAccess.get_sha256(path) != str(expected[path_value]):
			return false
	return true


func _require(condition: bool, message: String) -> bool:
	if condition:
		return true
	_failed = true
	push_error(message)
	return false


func _finish() -> void:
	quit(1 if _failed else 0)
